In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Ecommerce_Delivery_Analytics_New.csv")

# basic info
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

(100000, 11)
Index(['Order ID', 'Customer ID', 'Platform', 'Order Date & Time',
       'Delivery Time (Minutes)', 'Product Category', 'Order Value (INR)',
       'Customer Feedback', 'Service Rating', 'Delivery Delay',
       'Refund Requested'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Order ID                 100000 non-null  object
 1   Customer ID              100000 non-null  object
 2   Platform                 100000 non-null  object
 3   Order Date & Time        100000 non-null  object
 4   Delivery Time (Minutes)  100000 non-null  int64
 5   Product Category         100000 non-null  object
 6   Order Value (INR)        100000 non-null  int64
 7   Customer Feedback        100000 non-null  object
 8   Service Rating           100000 non-null  int64
 9   Delivery Delay           100000 non-null  object
 10  Refund Requested         100000 non-null  object
dtypes: int64(3), object(8)
memory usage: 8.4+ MB
None
       Delivery Time (Minutes)  Order Value (INR)  Service Rating
count            100000.000000      100000.000000   100000.000000
mean                 29.536140         590.994400        3.240790
std                   9.958933         417.409058        1.575962
min                   5.000000          50.000000        1.000000
25%                  23.000000         283.000000        2.000000
50%                  30.000000         481.000000        3.000000
75%                  36.000000         770.000000        5.000000
max                  76.000000        2000.000000        5.000000

In [2]:
df.head()

,Order ID,Customer ID,Platform,Order Date & Time,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested
0,ORD000001,CUST2824,JioMart,19:29.5,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,No,No
1,ORD000002,CUST1409,Blinkit,54:29.5,16,Dairy,279,Quick and reliable!,5,No,No
2,ORD000003,CUST5506,JioMart,21:29.5,25,Beverages,599,Items missing from order.,2,No,Yes
3,ORD000004,CUST5012,JioMart,19:29.5,42,Beverages,946,Items missing from order.,2,Yes,Yes
4,ORD000005,CUST4657,Blinkit,49:29.5,30,Beverages,334,"Fast delivery, great service!",5,No,No

# Data Cleaning

In [3]:
# convert datetime
df['Order Date & Time'] = pd.to_datetime(
    df['Order Date & Time'], 
    errors='coerce'
)

C:\Users\Rajni\AppData\Local\Temp\ipykernel_23012\2233383552.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Order Date & Time'] = pd.to_datetime(

In [4]:
# drop invalid rows
df = df.dropna(subset=['Order Date & Time'])

In [5]:
df.head()

,Order ID,Customer ID,Platform,Order Date & Time,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested
0,ORD000001,CUST2824,JioMart,2026-04-07 19:29:30,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,No,No
2,ORD000003,CUST5506,JioMart,2026-04-07 21:29:30,25,Beverages,599,Items missing from order.,2,No,Yes
3,ORD000004,CUST5012,JioMart,2026-04-07 19:29:30,42,Beverages,946,Items missing from order.,2,Yes,Yes
6,ORD000007,CUST2679,JioMart,2026-04-07 22:29:30,22,Personal Care,1693,"Fast delivery, great service!",5,No,No
9,ORD000010,CUST7912,JioMart,2026-04-07 08:29:30,51,Grocery,1279,"Very late delivery, not happy.",2,Yes,Yes

In [6]:
# creating time features
df['Order Date'] = df['Order Date & Time'].dt.date
df['Month'] = df['Order Date & Time'].dt.month
df['Hour'] = df['Order Date & Time'].dt.hour

In [7]:
df.head()

,Order ID,Customer ID,Platform,Order Date & Time,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested,Order Date,Month,Hour
0,ORD000001,CUST2824,JioMart,2026-04-07 19:29:30,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,No,No,2026-04-07,4,19
2,ORD000003,CUST5506,JioMart,2026-04-07 21:29:30,25,Beverages,599,Items missing from order.,2,No,Yes,2026-04-07,4,21
3,ORD000004,CUST5012,JioMart,2026-04-07 19:29:30,42,Beverages,946,Items missing from order.,2,Yes,Yes,2026-04-07,4,19
6,ORD000007,CUST2679,JioMart,2026-04-07 22:29:30,22,Personal Care,1693,"Fast delivery, great service!",5,No,No,2026-04-07,4,22
9,ORD000010,CUST7912,JioMart,2026-04-07 08:29:30,51,Grocery,1279,"Very late delivery, not happy.",2,Yes,Yes,2026-04-07,4,8

In [8]:
# convert categorical flags to numeric
df['Delivery Delay'] = df['Delivery Delay'].map({'Yes':1, 'No':0})
df['Refund Requested'] = df['Refund Requested'].map({'Yes':1, 'No':0})

In [9]:
df.head()

,Order ID,Customer ID,Platform,Order Date & Time,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested,Order Date,Month,Hour
0,ORD000001,CUST2824,JioMart,2026-04-07 19:29:30,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,0,0,2026-04-07,4,19
2,ORD000003,CUST5506,JioMart,2026-04-07 21:29:30,25,Beverages,599,Items missing from order.,2,0,1,2026-04-07,4,21
3,ORD000004,CUST5012,JioMart,2026-04-07 19:29:30,42,Beverages,946,Items missing from order.,2,1,1,2026-04-07,4,19
6,ORD000007,CUST2679,JioMart,2026-04-07 22:29:30,22,Personal Care,1693,"Fast delivery, great service!",5,0,0,2026-04-07,4,22
9,ORD000010,CUST7912,JioMart,2026-04-07 08:29:30,51,Grocery,1279,"Very late delivery, not happy.",2,1,1,2026-04-07,4,8

In [35]:
delay_counts = df['Delivery Delay'].value_counts()

print("Delivery Delay Counts:")
print(delay_counts)

Delivery Delay Counts:
Delivery Delay
0    34509
1     5402
Name: count, dtype: int64

In [36]:
refund_counts = df['Refund Requested'].value_counts()

print("\nRefund Requested Counts:")
print(refund_counts)

Refund Requested Counts:
Refund Requested
0    21654
1    18257
Name: count, dtype: int64

In [40]:
summary = pd.DataFrame({
    'status': ['Delivery Delay', 'Refund Requested'],
    'Count_1': [
        (df['Delivery Delay'] == 1).sum(),
        (df['Refund Requested'] == 1).sum()
    ],
    'Count_0': [
        (df['Delivery Delay'] == 0).sum(),
        (df['Refund Requested'] == 0).sum()
    ],
    'Percentage (%)': [
        df['Delivery Delay'].mean() * 100,
        df['Refund Requested'].mean() * 100
    ]
})

print(summary)

             status  Count_1  Count_0  Percentage (%)
0    Delivery Delay     5402    34509       13.535116
1  Refund Requested    18257    21654       45.744281

In [41]:
# check missing
print(df.isnull().sum())

Order ID                   0
Customer ID                0
Platform                   0
Order Date & Time          0
Delivery Time (Minutes)    0
Product Category           0
Order Value (INR)          0
Customer Feedback          0
Service Rating             0
Delivery Delay             0
Refund Requested           0
Order Date                 0
Month                      0
Hour                       0
dtype: int64

In [42]:
# drop duplicates
df = df.drop_duplicates()

In [43]:
df.head()

,Order ID,Customer ID,Platform,Order Date & Time,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested,Order Date,Month,Hour
0,ORD000001,CUST2824,JioMart,2026-04-07 19:29:30,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,0,0,2026-04-07,4,19
2,ORD000003,CUST5506,JioMart,2026-04-07 21:29:30,25,Beverages,599,Items missing from order.,2,0,1,2026-04-07,4,21
3,ORD000004,CUST5012,JioMart,2026-04-07 19:29:30,42,Beverages,946,Items missing from order.,2,1,1,2026-04-07,4,19
6,ORD000007,CUST2679,JioMart,2026-04-07 22:29:30,22,Personal Care,1693,"Fast delivery, great service!",5,0,0,2026-04-07,4,22
9,ORD000010,CUST7912,JioMart,2026-04-07 08:29:30,51,Grocery,1279,"Very late delivery, not happy.",2,1,1,2026-04-07,4,8

In [44]:
# revenue metrics
total_revenue = df['Order Value (INR)'].sum()
avg_order_value = df['Order Value (INR)'].mean()

# delivery metrics
avg_delivery_time = df['Delivery Time (Minutes)'].mean()
delay_rate = df['Delivery Delay'].mean() * 100

# refund metrics
refund_rate = df['Refund Requested'].mean() * 100

In [45]:
print(total_revenue, avg_order_value, avg_delivery_time, delay_rate, refund_rate)

23572207 590.6193029490616 29.529202475508004 13.535115632281828 45.74428102528125

In [46]:
rounded_values = {
    "Total Revenue": round(total_revenue, 2),
    "Avg Order Value": round(avg_order_value, 2),
    "Avg Delivery Time": round(avg_delivery_time, 2),
    "Delay Rate (%)": round(delay_rate, 2),
    "Refund Rate (%)": round(refund_rate, 2)
}

print(rounded_values)

{'Total Revenue': np.int64(23572207), 'Avg Order Value': np.float64(590.62), 'Avg Delivery Time': np.float64(29.53), 'Delay Rate (%)': np.float64(13.54), 'Refund Rate (%)': np.float64(45.74)}

# grouped analysis

In [47]:
# revenue by platform
platform_revenue = df.groupby('Platform')['Order Value (INR)'].sum().sort_values(ascending=False)

# revenue by category
category_revenue = df.groupby('Product Category')['Order Value (INR)'].sum().sort_values(ascending=False)

# delay vs rating
delay_rating = df.groupby('Delivery Delay')['Service Rating'].mean()

# refund vs delay
refund_delay = df.groupby('Delivery Delay')['Refund Requested'].mean()

# monthly sales
monthly_sales = df.groupby('Month')['Order Value (INR)'].sum()

In [48]:
print(platform_revenue)
print("--------------------------------")
print(category_revenue)
print("--------------------------------")
print(delay_rating) 
print("--------------------------------")
print(refund_delay) 
print("--------------------------------")
print(monthly_sales)

Platform
Swiggy Instamart    7908456
Blinkit             7864995
JioMart             7798756
Name: Order Value (INR), dtype: int64
--------------------------------
Product Category
Personal Care          6982093
Grocery                5719677
Beverages              3576038
Dairy                  2998220
Fruits & Vegetables    2476229
Snacks                 1819950
Name: Order Value (INR), dtype: int64
--------------------------------
Delivery Delay
0    3.246399
1    3.222325
Name: Service Rating, dtype: float64
--------------------------------
Delivery Delay
0    0.456548
1    0.463162
Name: Refund Requested, dtype: float64
--------------------------------
Month
4    23572207
Name: Order Value (INR), dtype: int64

In [49]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)